#!/bin/bash
echo "🔍 ANÁLISIS AUTOMÁTICO DEL PROYECTO"
echo "=================================="
echo "📁 Directorio: $(pwd)"
echo "📊 Archivos Kotlin: $(find . -name "*.kt" | wc -l)"
echo "📊 Archivos XML: $(find . -name "*.xml" | wc -l)"
echo "📊 Archivos Java: $(find . -name "*.java" | wc -l)"
echo "📊 Archivos HTML: $(find . -name "*.html" | wc -l)"
echo "📊 Archivos JS: $(find . -name "*.js" | wc -l)"
echo "📊 Archivos PS1: $(find . -name "*.ps1" | wc -l)"
echo "=================================="
echo "🎯 Proyectos principales encontrados:"
echo "  📱 BBMMessengerApp - App Android"
echo "  🌐 FimeTech - Sitio web"
echo "  🏪 Ferretería - E-commerce"
echo "  👶 FimeKids - Contenido infantil"
echo "=================================="
